### ISSUE TITLE
需要关注签名和证书什么的吗？

### ISSUE THREAD

**Issue by hrbwaxdoll** [Barbery/swiftpass#1]
用您的这个~

**Comment by Barbery** [comment]
签名那些都封装好的了，请查看readme的使用说明即可，设置好配置参数调用即可

**Comment by hrbwaxdoll** [comment]
感谢回复，另外在composer的时候，出现了问题，就是Installing guzzlehttp/guzzle (6.5.x-dev 400cefd
)这个版本无法安装，不知道为什么，而且现在Guzzle也出到了7.x，是否可以更新下~

Barbery <notifications@github.com> 于2020年3月31日周二 下午11:01写道：

**Comment by Barbery** [comment]
目前guzzle的7.x还是beta版本，暂时不考虑更新。目前对guzzle的依赖是>6.2.* <7.0即可

**Comment by hrbwaxdoll** [comment]
Warning: openssl_sign(): supplied key param cannot be coerced into a private key in /www/wwwroot/xxx.com/phalapi/src/app/Domain/Pays.php on line 104

Warning: openssl_free_key() expects parameter 1 to be resource, bool given in /www/wwwroot/xxx.com/phalapi/src/app/Domain/Pays.php on line 105

这两个错误一直在~
